name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  docker_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t alnikyur/ping_bot:latest -f docker/Dockerfile . && \
           mkdir -p /opt/artifact/
           
    - name: Upload artifacts
      run: docker save alnikyur/ping_bot:latest -o /opt/artifact/ping_bot.tar

#    - run: mkdir -p /opt/artifact/
#    - run: docker save alnikyur/ping_bot:latest -o /opt/artifact/ping_bot.tar
    - uses: actions/upload-artifact@v3
      with:
        name: ping_bot_test
        path: /opt/artifact/
#    - name: Test dockerfile
#    - run: docker run --rm --name ping_bot_tmp -i alnikyur/ping_bot:latest sh -c "python3 --version"

  docker_test:

    runs-on: ubuntu-latest
    needs: docker_build
    steps:
    - uses: actions/checkout@v3
    - name: Import images
    - uses: actions/download-artifact@v3
      with:
        name: ping_bot_test
        path: /opt/artifact/
      run: docker import /opt/artifact/ping_bot.tar ping_bot:test
    - name: Run tests
      run: docker run --rm --name ping_bot_tmp -i ping_bot:test sh -c "python3 --version"
